export enum IDPayServiceID {
  OK = "TESTSRV01",
  ERR_NOT_ELIGIBLE = "TESTSRV02",
  ERR_NO_REQUIREMENTS = "TESTSRV03",
  ERR_ONBOARDED = "TESTSRV04",
  ERR_UNSUBSCRIBED = "TESTSRV05",
  ERR_ON_EVALUATION = "TESTSRV06",
  OK_INVITED = "TESTSRV07",
  ERR_BUDGET_TERMINATED = "TESTSRV08",
  ERR_ENDED = "TESTSRV09",
  ERR_NOT_STARTED = "TESTSRV10",
  ERR_SUSPENDED = "TESTSRV11",
  OK_NO_PREREQUISITES = "TESTSRV12",
  OK_PDND_ONLY = "TESTSRV13",
  OK_SELF_ONLY = "TESTSRV14",
  OK_SELF_MULTI_ONLY = "TESTSRV15",
  OK_SELF_BOOL_ONLY = "TESTSRV16"
}

export enum IDPayInitiativeID {
  OK = "TESTINIT01",
  ERR_NOT_ELIGIBLE = "TESTINIT02",
  ERR_NO_REQUIREMENTS = "TESTINIT03",
  ERR_ONBOARDED = "TESTINIT04",
  ERR_UNSUBSCRIBED = "TESTINIT05",
  ERR_ON_EVALUATION = "TESTINIT06",
  OK_INVITED = "TESTINIT07",
  ERR_BUDGET_TERMINATED = "TESTINIT08",
  ERR_ENDED = "TESTINIT09",
  ERR_NOT_STARTED = "TESTINIT10",
  ERR_SUSPENDED = "TESTINIT11",
  OK_NO_PREREQUISITES = "TESTINIT12",
  OK_PDND_ONLY = "TESTINIT13",
  OK_SELF_ONLY = "TESTINIT14",
  OK_SELF_MULTI_ONLY = "TESTINIT15",
  OK_SELF_BOOL_ONLY = "TESTINIT16"
}

export const onboardableInitiativesIDs: ReadonlyArray<IDPayInitiativeID> = [
  IDPayInitiativeID.OK,
  IDPayInitiativeID.OK_INVITED,
  IDPayInitiativeID.OK_NO_PREREQUISITES,
  IDPayInitiativeID.OK_PDND_ONLY,
  IDPayInitiativeID.OK_SELF_ONLY,
  IDPayInitiativeID.OK_SELF_MULTI_ONLY,
  IDPayInitiativeID.OK_SELF_BOOL_ONLY
];
