export enum IDPayServiceID {
  OK = "TESTSRV0",
  ERR_NOT_ELIGIBLE = "TESTSRV1",
  ERR_NO_REQUIREMENTS = "TESTSRV2",
  ERR_ONBOARDED = "TESTSRV3",
  ERR_UNSUBSCRIBED = "TESTSRV4",
  ERR_ON_EVALUATION = "TESTSRV5",
  OK_INVITED = "TESTSRV6",
  ERR_BUDGET_TERMINATED = "TESTSRV7",
  ERR_ENDED = "TESTSRV8",
  ERR_NOT_STARTED = "TESTSRV9",
  ERR_SUSPENDED = "TESTSRV10",
  OK_NO_PREREQUISITES = "TESTSRV11",
  OK_PDND_ONLY = "TESTSRV12",
  OK_SELF_ONLY = "TESTSRV13",
  OK_SELF_MULTI_ONLY = "TESTSRV14",
  OK_SELF_BOOL_ONLY = "TESTSRV15"
}

export enum IDPayInitiativeID {
  OK = "TESTINIT0",
  ERR_NOT_ELIGIBLE = "TESTINIT1",
  ERR_NO_REQUIREMENTS = "TESTINIT2",
  ERR_ONBOARDED = "TESTINIT3",
  ERR_UNSUBSCRIBED = "TESTINIT4",
  ERR_ON_EVALUATION = "TESTINIT5",
  OK_INVITED = "TESTINIT6",
  ERR_BUDGET_TERMINATED = "TESTINIT7",
  ERR_ENDED = "TESTINIT8",
  ERR_NOT_STARTED = "TESTINIT9",
  ERR_SUSPENDED = "TESTINIT10",
  OK_NO_PREREQUISITES = "TESTINIT11",
  OK_PDND_ONLY = "TESTINIT12",
  OK_SELF_ONLY = "TESTINIT13",
  OK_SELF_MULTI_ONLY = "TESTINIT14",
  OK_SELF_BOOL_ONLY = "TESTINIT15"
}

export const onboardableInitiativesIDs: ReadonlyArray<IDPayInitiativeID> = [
  IDPayInitiativeID.OK,
  IDPayInitiativeID.OK_INVITED,
  IDPayInitiativeID.OK_NO_PREREQUISITES,
  IDPayInitiativeID.OK_PDND_ONLY,
  IDPayInitiativeID.OK_SELF_ONLY,
  IDPayInitiativeID.OK_SELF_MULTI_ONLY,
  IDPayInitiativeID.OK_SELF_BOOL_ONLY
];
