swagger: '2.0'
info:
  title: IO Sign - Backend API
  version: 0.0.1
host: app-backend.io.italia.it
basePath: /api/v1/fci
schemes:
  - https
paths:
  /qtsp/clauses:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: The QTSP clauses list
          schema:
            $ref: '#/definitions/QtspClausesMetadata'
        '403':
          $ref: "#/x-components/responses/Forbidden"
        '404':
          $ref: "#/x-components/responses/NotFound"
      operationId: getQtspClausesMetadata
      summary: Get clauses list and MRC from QTSP
  '/signature-requests/{id}':
    get:
      produces:
        - application/json
      parameters:
        - description: Entity Id
          format: ulid
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: The Signature Request detail
          schema:
            $ref: '#/definitions/SignatureRequestDetailView'
        '403':
          $ref: "#/x-components/responses/Forbidden"
        '404':
          $ref: "#/x-components/responses/NotFound"
      operationId: getSignatureRequestById
      summary: Get a Signature Request By Id
  /signatures:
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateSignatureBody'
      responses:
        '201':
          description: Signature created
        '400':
          $ref: "#/x-components/responses/BadRequest"
        '403':
          $ref: "#/x-components/responses/Forbidden"
        default:
          $ref: "#/x-components/responses/Unexpected"
      operationId: createSignature
      summary: Create a Signature from SignatureRequest
definitions:
  Clause:
    properties:
      title:
        type: string
      type:
        $ref: '#/definitions/ClausesType'
    required:
      - title
      - type
    type: object
  ClausesSignature:
    description: accepted signature clause
    properties:
      attrs:
        description: 'uniqueName or base64(Coords) base64({x,y,w,h,page})'
        type: string
      type:
        $ref: '#/definitions/ClausesSignatureType'
    required:
      - type
      - attrs
  ClausesSignatureType:
    type: string
    x-extensible-enum:
      - COORDS
      - UNIQUE_NAME
  ClausesType:
    description: >
      Signature request status:

      * `REQUIRED` - The clause is mandatory and the user sees it already
      accepted.

      * `UNFAIR` - The clause is unfair and the user must explicitly accept it
      to continue

      * `OPTIONAL` - The clause is optional and the user can also decide not to
      accept it
    type: string
    x-extensible-enum:
      - REQUIRED
      - UNFAIR
      - OPTIONAL
  CreateSignatureBody:
    properties:
      document_signatures:
        items:
          $ref: '#/definitions/DocumentSignature'
        minItems: 1
        type: array
        uniqueItems: true
      public_key_digest:
        $ref: '#/definitions/PublicKeyDigest'
      qtsp_clauses:
        $ref: '#/definitions/QtspClauses'
      signature_request_id:
        $ref: '#/definitions/Id'
      timestamp:
        $ref: '#/definitions/Timestamp'
    required:
      - signature_request_id
      - public_key_digest
      - document_signatures
      - qtsp_clauses
      - timestamp
    type: object
  Document:
    properties:
      created_at:
        $ref: '#/definitions/Timestamp'
      id:
        $ref: '#/definitions/Id'
      metadata:
        $ref: '#/definitions/DocumentMetadata'
      updated_at:
        $ref: '#/definitions/Timestamp'
    required:
      - id
      - status
      - metadata
      - created_at
      - updated_at
    type: object
  DocumentMetadata:
    properties:
      signature_fields:
        items:
          $ref: '#/definitions/SignatureField'
        type: array
      title:
        type: string
    type: object
  DocumentSignature:
    properties:
      clauses:
        items:
          $ref: '#/definitions/ClausesSignature'
        type: array
      document_id:
        format: ulid
        type: string
      signature:
        description: Signature of document digest concatenated with document clauses
        format: base64url
        type: string
    required:
      - document_id
      - signature
      - clauses
    type: object
  DocumentUploaded:
    allOf:
      - $ref: '#/definitions/Document'
      - properties:
          status:
            enum:
              - READY
            type: string
          uploaded_at:
            $ref: '#/definitions/Timestamp'
          url:
            format: uri
            type: string
        required:
          - status
          - uploaded_at
          - url
        type: object
  ForwardedSignatureRequestStatus:
    description: >
      Signature request status:

      * `WAIT_FOR_SIGNATURE` - The signature request has been sent to the user
      and is awaiting signature

      * `SIGNED` - The signature request was successfully signed.
    type: string
    x-extensible-enum:
      - WAIT_FOR_SIGNATURE
      - SIGNED
  Id:
    description: Entity Id
    example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
    format: ulid
    type: string
  PublicKeyDigest:
    description: Hash of PEM public key encoded in base64
    format: base64url
    type: string
  QtspClause:
    properties:
      text:
        type: string
    required:
      - text
    type: object
  QtspClauses:
    properties:
      accepted_clauses:
        items:
          $ref: '#/definitions/QtspClause'
        minItems: 1
        type: array
        uniqueItems: true
      filled_mrc_document_url:
        format: uri
        type: string
      signature:
        description: Signature of MRC digest concatenated with QTSP accepted clauses
        format: base64url
        type: string
    required:
      - accepted_clauses
      - filled_mrc_document_url
      - signature
    type: object
  QtspClausesMetadata:
    properties:
      clauses:
        items:
          $ref: '#/definitions/QtspClause'
        minItems: 1
        type: array
        uniqueItems: true
      mrc_document_url:
        format: uri
        type: string
      privacy_document_url:
        format: uri
        type: string
      tos_document_url:
        format: uri
        type: string
    required:
      - clauses
      - mrc_document_url
      - privacy_document_url
      - tos_document_url
    type: object
  SignatureField:
    properties:
      attrs:
        type: object
      clause:
        $ref: '#/definitions/Clause'
    required:
      - unique_name
      - clause
    type: object
  SignatureFieldAttributes:
    properties:
      unique_name:
        type: string
    type: object
  SignatureFieldToBeCreatedAttributes:
    properties:
      coordinates:
        properties:
          x:
            minimum: 0
            type: number
          'y':
            minimum: 0
            type: number
        type: object
      page:
        minimum: 0
        type: number
      size:
        properties:
          h:
            minimum: 0
            type: number
          w:
            minimum: 0
            type: number
        type: object
    type: object
  SignatureRequestDetailView:
    properties:
      documents:
        items:
          $ref: '#/definitions/DocumentUploaded'
        type: array
      expires_at:
        $ref: '#/definitions/Timestamp'
      id:
        $ref: '#/definitions/Id'
      status:
        $ref: '#/definitions/ForwardedSignatureRequestStatus'
    required:
      - id
      - expires_at
      - status
      - documents
    type: object
  Timestamp:
    description: A date-time field in ISO-8601 format and UTC timezone.
    example: '2018-10-13T00:00:00.000Z'
    format: UTCISODateFromString
    type: string
    x-import: '@pagopa/ts-commons/lib/dates'
  ProblemJson:
    properties:
      detail:
        description: |-
          A human readable explanation specific to this occurrence of the
          problem.
        example: There was an error processing the request
        type: string
      instance:
        description: >-
          An absolute URI that identifies the specific occurrence of the
          problem. It may or may not yield further information if dereferenced.
        format: uri
        type: string
      status:
        description: >-
          The HTTP status code generated by the origin server for this
          occurrence of the problem.
        example: 200
        exclusiveMaximum: true
        format: int32
        maximum: 600
        minimum: 100
        type: integer
      title:
        description: |-
          A short, summary of the problem type. Written in english and readable
          for engineers (usually not suited for non technical stakeholders and
          not localized); example: Service Unavailable
        type: string
      type:
        default: 'about:blank'
        description: |-
          An absolute URI that identifies the problem type. When dereferenced,
          it SHOULD provide human-readable documentation for the problem type
          (e.g., using HTML).
        example: 'https://example.com/problem/constraint-violation'
        format: uri
        type: string
    required:
      - title
      - status
      - detail
    type: object
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
security:
  - Bearer: []
x-components:
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/definitions/ProblemJson'
      description: Validation error on body
    Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/definitions/ProblemJson'
      description: You don't have enough privileges to perform this action
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/definitions/ProblemJson'
      description: The specified resource was not found
    Unexpected:
      content:
        application/json:
          schema:
            $ref: '#/definitions/ProblemJson'
      description: Unexpected error
