import SwaggerParser from "swagger-parser";
import { OpenAPIV2 } from "openapi-types";
import * as prettier from "prettier";

const tsSpecFilePaths = "./generated/definitions/server_paths.ts";
export const saveApiPaths = async () => {
  const document = await SwaggerParser.bundle(
    "https://raw.githubusercontent.com/teamdigitale/italia-backend/v1.7.1/api_backend.yaml"
  );

  const basePath = (document as OpenAPIV2.Document).basePath;
  const paths = Object.keys(document.paths).map(p =>
    p.replace("{", ":").replace("}", "")
  );

  const specCode = `
    /* tslint:disable:object-literal-sort-keys */
    // DO NOT EDIT
    // this file is autogenerated;
    // this file represents all availables API paths exposed by IO backend
  
    export const basePath = "${basePath}";
    export type SupportedMethod = "get" | "post" | "put" | "delete" | "update";
    export type IOApiPath = ${paths.map(p => `"${p}"`).join(" | ")};
    `;

  const fs = require("fs");
  if (tsSpecFilePaths) {
    await fs.writeFile(
      tsSpecFilePaths,
      prettier.format(specCode, {
        parser: "typescript"
      }),
      (_: any, __: any) => {
        console.log();
      }
    );
  }
};

saveApiPaths().then(() => console.log("API Paths saved!"));
