on:
  - pull_request
jobs:
  checks:
    runs-on: ubuntu-latest
    environment: dev
    concurrency:
      group: ${{ github.workflow }}-pr-staticcheck-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - id: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - id: setup-node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: '.node-version'
      - id: yarn-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-
      - id: install-packages
        run: yarn install --frozen-lockfile
        shell: bash
      - id: generate-api-client
        run: yarn generate
        shell: bash
      - id: run-tsc
        run: yarn tsc:noemit
      - id: run-lint
        run: yarn lint
      - id: run-prettier
        run: yarn prettier:check
      - id: run-test
        run: yarn test:ci
      - id: coverage
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
